import Footer from "./components/footer/Footer";
import Header from "./components/header/Header";
import "./globals.css";

export const metadata = {
  title: "Online do'koni",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />

        <div className="min-h-[calc(100vh-100px)] pt-[70px]">{children}</div>

        <Footer />
      </body>
    </html>
  );
}
